version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www1_quimerico:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=www1.quimerico.uy
      - LETSENCRYPT_HOST=www1.quimerico.uy
      - LETSENCRYPT_EMAIL=hola@quimerico.uy

  www2_quimerico:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./html2:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=www2.quimerico.uy
      - LETSENCRYPT_HOST=www2.quimerico.uy
      - LETSENCRYPT_EMAIL=hola@quimerico.uy

